# Generated by Django 3.1.4 on 2021-12-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esr21_pharmacy', '0002_auto_20211206_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signatures',
            name='designation',
            field=models.CharField(choices=[('Pharmacy personnel at BHP', 'Pharmacy personnel at BHP'), ('Pharmacy Personnel at study site', 'Pharmacy Personnel at study site'), ('Indicator Manager/ Destruction monitor', 'Indicator Manager/ Destruction monitor')], max_length=50, verbose_name='Designation'),
        ),
    ]
