# Generated by Django 3.1.4 on 2021-12-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esr21_pharmacy', '0003_auto_20211206_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drugrequisition',
            options={'verbose_name': 'Drug Accountability', 'verbose_name_plural': 'Drug Accountability'},
        ),
        migrations.AlterField(
            model_name='drugaccountabilitylog',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='signatures',
            name='designation',
            field=models.CharField(choices=[('Pharmacy Personnel at study site', 'Pharmacy Personnel at study site'), ('Indicator Manager/ Destruction monitor', 'Indicator Manager/ Destruction monitor'), ('Pharmacy personnel at BHP', 'Pharmacy personnel at BHP')], max_length=50, verbose_name='Designation'),
        ),
    ]
