# Generated by Django 3.1.4 on 2021-12-08 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esr21_pharmacy', '0004_auto_20211208_0748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drugrequisition',
            options={'verbose_name': 'Drug Requisition', 'verbose_name_plural': 'Drug Requisition'},
        ),
    ]
