# Generated by Django 3.1.4 on 2021-12-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esr21_pharmacy', '0005_auto_20211208_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugrequisition',
            name='acceptable_temp_range',
        ),
        migrations.RemoveField(
            model_name='drugrequisition',
            name='delivery_site_temp',
        ),
        migrations.RemoveField(
            model_name='drugrequisition',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='drugrequisition',
            name='investigator',
        ),
        migrations.RemoveField(
            model_name='drugrequisition',
            name='last_dose_temp',
        ),
        migrations.RemoveField(
            model_name='drugrequisition',
            name='ordered_by_date_time',
        ),
        migrations.RemoveField(
            model_name='drugrequisition',
            name='study_product_name',
        ),
        migrations.RemoveField(
            model_name='drugrequisition',
            name='study_product_ordered_by',
        ),
        migrations.RemoveField(
            model_name='drugrequisition',
            name='temp_control_during_trans',
        ),
        migrations.RemoveField(
            model_name='drugrequisition',
            name='title',
        ),
        migrations.RemoveField(
            model_name='drugrequisition',
            name='transportation_control_comment',
        ),
        migrations.RemoveField(
            model_name='drugrequisition',
            name='units',
        ),
        migrations.AlterField(
            model_name='signatures',
            name='designation',
            field=models.CharField(choices=[('Pharmacy personnel at BHP', 'Pharmacy personnel at BHP'), ('Pharmacy Personnel at study site', 'Pharmacy Personnel at study site'), ('Indicator Manager/ Destruction monitor', 'Indicator Manager/ Destruction monitor')], max_length=50, verbose_name='Designation'),
        ),
    ]
