# Generated by Django 3.1.4 on 2021-12-08 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esr21_pharmacy', '0006_auto_20211208_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosagespillage',
            name='drug',
        ),
        migrations.RemoveField(
            model_name='drugnotification',
            name='reasons_for_treatment_discontinuation',
        ),
        migrations.DeleteModel(
            name='DrugOrdering',
        ),
        migrations.RemoveField(
            model_name='historicaldosagespillage',
            name='drug',
        ),
        migrations.RemoveField(
            model_name='historicaldosagespillage',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='signatures',
            name='notification',
        ),
        migrations.DeleteModel(
            name='DosageSpillage',
        ),
        migrations.DeleteModel(
            name='DrugDisposal',
        ),
        migrations.DeleteModel(
            name='DrugDoseAdministration',
        ),
        migrations.DeleteModel(
            name='DrugNotification',
        ),
        migrations.DeleteModel(
            name='HistoricalDosageSpillage',
        ),
        migrations.DeleteModel(
            name='Signatures',
        ),
    ]
